spring:
  application:
    name: billing-service
  profiles:
    active: development
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      username: user
      password: password
      label: master

server:
  port: 4001
grpc:
  server:
    port: 9001
management:
  endpoints:
    web:
      exposure:
        include: refresh
billing:
  greeting: Hey billing
