billing:
  service:
    address: billing-service
    grpc:
      port: 9001
server:
  port: 4000
logging:
  level:
    root: info
spring:
  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://config-service:8888
        request-connect-timeout: 5000
        request-read-timeout: 5000
        fail-fast: true
        retry:
          max-attempts: 6
          initial-interval: 1000
          max-interval: 2000
          multiplier: 1.1
        username: user
        password: password
        label: master
  datasource:
    password: password
    url: jdbc:postgresql://patient-service-db:5432/db
    username: admin_user
  jpa:
    hibernate:
      ddl:
        auto: update
  kafka:
    bootstrap:
      servers: kafka:9092,kafka:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: refresh
patient:
  greeting: Hey patient
